server:
  port: 8010

#spring
spring:
  application:
    name: article-service
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml
    enabled: false
    default-schema: post
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 9GA-UXi-jUI-@RU
    url: jdbc:postgresql://localhost:5432/bugawa_post_service_db
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

#Приложение
app:
  api:
    path: "/api"
    v1:
      post:
        articles: "/v1/post/articles"
        reviews: "/v1/post/reviews"

#openapi
springdoc:
  api-docs:
    path: "/openapi"
  show-actuator: false
  swagger-ui:
    path: swagger-ui.html
    disable-swagger-default-url: true
